export default [
  {
    id: '110000',
    name: '北京',
    parent_id: '1',
    listorder: '1',
    children: [
      {
        id: '110100',
        name: '北京市',
        parent_id: '110000',
        listorder: '1',
        children: [
          {
            id: '110114',
            name: '昌平区',
            parent_id: '110100',
            listorder: '1',
          },
          {
            id: '110105',
            name: '朝阳区',
            parent_id: '110100',
            listorder: '2',
          },
          {
            id: '110101',
            name: '东城区',
            parent_id: '110100',
            listorder: '3',
          },
          {
            id: '110115',
            name: '大兴区',
            parent_id: '110100',
            listorder: '4',
          },
          {
            id: '110111',
            name: '房山区',
            parent_id: '110100',
            listorder: '5',
          },
          {
            id: '110106',
            name: '丰台区',
            parent_id: '110100',
            listorder: '6',
          },
          {
            id: '110108',
            name: '海淀区',
            parent_id: '110100',
            listorder: '7',
          },
          {
            id: '110116',
            name: '怀柔区',
            parent_id: '110100',
            listorder: '8',
          },
          {
            id: '110109',
            name: '门头沟区',
            parent_id: '110100',
            listorder: '9',
          },
          {
            id: '110228',
            name: '密云县',
            parent_id: '110100',
            listorder: '10',
          },
          {
            id: '110117',
            name: '平谷区',
            parent_id: '110100',
            listorder: '11',
          },
          {
            id: '110107',
            name: '石景山区',
            parent_id: '110100',
            listorder: '12',
          },
          {
            id: '110113',
            name: '顺义区',
            parent_id: '110100',
            listorder: '13',
          },
          {
            id: '110112',
            name: '通州区',
            parent_id: '110100',
            listorder: '14',
          },
          {
            id: '110102',
            name: '西城区',
            parent_id: '110100',
            listorder: '15',
          },
          {
            id: '110229',
            name: '延庆县',
            parent_id: '110100',
            listorder: '16',
          },
        ],
      },
    ],
  },
  {
    id: '120000',
    name: '天津',
    parent_id: '1',
    listorder: '2',
    children: [
      {
        id: '120100',
        name: '天津市',
        parent_id: '120000',
        listorder: '1',
        children: [
          {
            id: '120115',
            name: '宝坻区',
            parent_id: '120100',
            listorder: '1',
          },
          {
            id: '120113',
            name: '北辰区',
            parent_id: '120100',
            listorder: '2',
          },
          {
            id: '120116',
            name: '滨海新区',
            parent_id: '120100',
            listorder: '3',
          },
          {
            id: '120110',
            name: '东丽区',
            parent_id: '120100',
            listorder: '4',
          },
          {
            id: '120105',
            name: '河北区',
            parent_id: '120100',
            listorder: '5',
          },
          {
            id: '120102',
            name: '河东区',
            parent_id: '120100',
            listorder: '6',
          },
          {
            id: '120101',
            name: '和平区',
            parent_id: '120100',
            listorder: '7',
          },
          {
            id: '120103',
            name: '河西区',
            parent_id: '120100',
            listorder: '8',
          },
          {
            id: '120106',
            name: '红桥区',
            parent_id: '120100',
            listorder: '9',
          },
          {
            id: '120223',
            name: '静海县',
            parent_id: '120100',
            listorder: '10',
          },
          {
            id: '120112',
            name: '津南区',
            parent_id: '120100',
            listorder: '11',
          },
          {
            id: '120225',
            name: '蓟县',
            parent_id: '120100',
            listorder: '12',
          },
          {
            id: '120104',
            name: '南开区',
            parent_id: '120100',
            listorder: '13',
          },
          {
            id: '120221',
            name: '宁河县',
            parent_id: '120100',
            listorder: '14',
          },
          {
            id: '120114',
            name: '武清区',
            parent_id: '120100',
            listorder: '15',
          },
          {
            id: '120111',
            name: '西青区',
            parent_id: '120100',
            listorder: '16',
          },
        ],
      },
    ],
  },
  {
    id: '130000',
    name: '河北省',
    parent_id: '1',
    listorder: '3',
    children: [
      {
        id: '130600',
        name: '保定市',
        parent_id: '130000',
        listorder: '1',
        children: [
          {
            id: '130683',
            name: '安国市',
            parent_id: '130600',
            listorder: '1',
          },
          {
            id: '130632',
            name: '安新县',
            parent_id: '130600',
            listorder: '2',
          },
          {
            id: '130603',
            name: '北市区',
            parent_id: '130600',
            listorder: '3',
          },
          {
            id: '130637',
            name: '博野县',
            parent_id: '130600',
            listorder: '4',
          },
          {
            id: '130626',
            name: '定兴县',
            parent_id: '130600',
            listorder: '5',
          },
          {
            id: '130682',
            name: '定州市',
            parent_id: '130600',
            listorder: '6',
          },
          {
            id: '130624',
            name: '阜平县',
            parent_id: '130600',
            listorder: '7',
          },
          {
            id: '130684',
            name: '高碑店市',
            parent_id: '130600',
            listorder: '8',
          },
          {
            id: '130628',
            name: '高阳县',
            parent_id: '130600',
            listorder: '9',
          },
          {
            id: '130623',
            name: '涞水县',
            parent_id: '130600',
            listorder: '10',
          },
          {
            id: '130630',
            name: '涞源县',
            parent_id: '130600',
            listorder: '11',
          },
          {
            id: '130635',
            name: '蠡县',
            parent_id: '130600',
            listorder: '12',
          },
          {
            id: '130621',
            name: '满城县',
            parent_id: '130600',
            listorder: '13',
          },
          {
            id: '130604',
            name: '南市区',
            parent_id: '130600',
            listorder: '14',
          },
          {
            id: '130622',
            name: '清苑县',
            parent_id: '130600',
            listorder: '15',
          },
          {
            id: '130634',
            name: '曲阳县',
            parent_id: '130600',
            listorder: '16',
          },
          {
            id: '130629',
            name: '容城县',
            parent_id: '130600',
            listorder: '17',
          },
          {
            id: '130636',
            name: '顺平县',
            parent_id: '130600',
            listorder: '18',
          },
          {
            id: '130627',
            name: '唐县',
            parent_id: '130600',
            listorder: '19',
          },
          {
            id: '130631',
            name: '望都县',
            parent_id: '130600',
            listorder: '20',
          },
          {
            id: '130602',
            name: '新市区',
            parent_id: '130600',
            listorder: '21',
          },
          {
            id: '130638',
            name: '雄县',
            parent_id: '130600',
            listorder: '22',
          },
          {
            id: '130625',
            name: '徐水县',
            parent_id: '130600',
            listorder: '23',
          },
          {
            id: '130633',
            name: '易县',
            parent_id: '130600',
            listorder: '24',
          },
          {
            id: '130681',
            name: '涿州市',
            parent_id: '130600',
            listorder: '25',
          },
        ],
      },
      {
        id: '130900',
        name: '沧州市',
        parent_id: '130000',
        listorder: '2',
        children: [
          {
            id: '130981',
            name: '泊头市',
            parent_id: '130900',
            listorder: '1',
          },
          {
            id: '130921',
            name: '沧县',
            parent_id: '130900',
            listorder: '2',
          },
          {
            id: '130923',
            name: '东光县',
            parent_id: '130900',
            listorder: '3',
          },
          {
            id: '130924',
            name: '海兴县',
            parent_id: '130900',
            listorder: '4',
          },
          {
            id: '130984',
            name: '河间市',
            parent_id: '130900',
            listorder: '5',
          },
          {
            id: '130983',
            name: '黄骅市',
            parent_id: '130900',
            listorder: '6',
          },
          {
            id: '130930',
            name: '孟村回族自治县',
            parent_id: '130900',
            listorder: '7',
          },
          {
            id: '130927',
            name: '南皮县',
            parent_id: '130900',
            listorder: '8',
          },
          {
            id: '130922',
            name: '青县',
            parent_id: '130900',
            listorder: '9',
          },
          {
            id: '130982',
            name: '任丘市',
            parent_id: '130900',
            listorder: '10',
          },
          {
            id: '130926',
            name: '肃宁县',
            parent_id: '130900',
            listorder: '11',
          },
          {
            id: '130928',
            name: '吴桥县',
            parent_id: '130900',
            listorder: '12',
          },
          {
            id: '130929',
            name: '献县',
            parent_id: '130900',
            listorder: '13',
          },
          {
            id: '130902',
            name: '新华区',
            parent_id: '130900',
            listorder: '14',
          },
          {
            id: '130925',
            name: '盐山县',
            parent_id: '130900',
            listorder: '15',
          },
          {
            id: '130903',
            name: '运河区',
            parent_id: '130900',
            listorder: '16',
          },
        ],
      },
      {
        id: '130800',
        name: '承德市',
        parent_id: '130000',
        listorder: '3',
        children: [
          {
            id: '130821',
            name: '承德县',
            parent_id: '130800',
            listorder: '1',
          },
          {
            id: '130826',
            name: '丰宁满族自治县',
            parent_id: '130800',
            listorder: '2',
          },
          {
            id: '130827',
            name: '宽城满族自治县',
            parent_id: '130800',
            listorder: '3',
          },
          {
            id: '130825',
            name: '隆化县',
            parent_id: '130800',
            listorder: '4',
          },
          {
            id: '130824',
            name: '滦平县',
            parent_id: '130800',
            listorder: '5',
          },
          {
            id: '130823',
            name: '平泉县',
            parent_id: '130800',
            listorder: '6',
          },
          {
            id: '130803',
            name: '双滦区',
            parent_id: '130800',
            listorder: '7',
          },
          {
            id: '130802',
            name: '双桥区',
            parent_id: '130800',
            listorder: '8',
          },
          {
            id: '130828',
            name: '围场满族蒙古族自治县',
            parent_id: '130800',
            listorder: '9',
          },
          {
            id: '130822',
            name: '兴隆县',
            parent_id: '130800',
            listorder: '10',
          },
          {
            id: '130804',
            name: '鹰手营子矿区',
            parent_id: '130800',
            listorder: '11',
          },
        ],
      },
      {
        id: '130400',
        name: '邯郸市',
        parent_id: '130000',
        listorder: '4',
        children: [
          {
            id: '130424',
            name: '成安县',
            parent_id: '130400',
            listorder: '1',
          },
          {
            id: '130427',
            name: '磁县',
            parent_id: '130400',
            listorder: '2',
          },
          {
            id: '130403',
            name: '丛台区',
            parent_id: '130400',
            listorder: '3',
          },
          {
            id: '130425',
            name: '大名县',
            parent_id: '130400',
            listorder: '4',
          },
          {
            id: '130428',
            name: '肥乡县',
            parent_id: '130400',
            listorder: '5',
          },
          {
            id: '130406',
            name: '峰峰矿区',
            parent_id: '130400',
            listorder: '6',
          },
          {
            id: '130404',
            name: '复兴区',
            parent_id: '130400',
            listorder: '7',
          },
          {
            id: '130432',
            name: '广平县',
            parent_id: '130400',
            listorder: '8',
          },
          {
            id: '130433',
            name: '馆陶县',
            parent_id: '130400',
            listorder: '9',
          },
          {
            id: '130421',
            name: '邯郸县',
            parent_id: '130400',
            listorder: '10',
          },
          {
            id: '130402',
            name: '邯山区',
            parent_id: '130400',
            listorder: '11',
          },
          {
            id: '130431',
            name: '鸡泽县',
            parent_id: '130400',
            listorder: '12',
          },
          {
            id: '130423',
            name: '临漳县',
            parent_id: '130400',
            listorder: '13',
          },
          {
            id: '130430',
            name: '邱县',
            parent_id: '130400',
            listorder: '14',
          },
          {
            id: '130435',
            name: '曲周县',
            parent_id: '130400',
            listorder: '15',
          },
          {
            id: '130426',
            name: '涉县',
            parent_id: '130400',
            listorder: '16',
          },
          {
            id: '130434',
            name: '魏县',
            parent_id: '130400',
            listorder: '17',
          },
          {
            id: '130481',
            name: '武安市',
            parent_id: '130400',
            listorder: '18',
          },
          {
            id: '130429',
            name: '永年县',
            parent_id: '130400',
            listorder: '19',
          },
        ],
      },
      {
        id: '131100',
        name: '衡水市',
        parent_id: '130000',
        listorder: '5',
        children: [
          {
            id: '131125',
            name: '安平县',
            parent_id: '131100',
            listorder: '1',
          },
          {
            id: '131128',
            name: '阜城县',
            parent_id: '131100',
            listorder: '2',
          },
          {
            id: '131126',
            name: '故城县',
            parent_id: '131100',
            listorder: '3',
          },
          {
            id: '131127',
            name: '景县',
            parent_id: '131100',
            listorder: '4',
          },
          {
            id: '131181',
            name: '冀州市',
            parent_id: '131100',
            listorder: '5',
          },
          {
            id: '131124',
            name: '饶阳县',
            parent_id: '131100',
            listorder: '6',
          },
          {
            id: '131182',
            name: '深州市',
            parent_id: '131100',
            listorder: '7',
          },
          {
            id: '131102',
            name: '桃城区',
            parent_id: '131100',
            listorder: '8',
          },
          {
            id: '131123',
            name: '武强县',
            parent_id: '131100',
            listorder: '9',
          },
          {
            id: '131122',
            name: '武邑县',
            parent_id: '131100',
            listorder: '10',
          },
          {
            id: '131121',
            name: '枣强县',
            parent_id: '131100',
            listorder: '11',
          },
        ],
      },
      {
        id: '131000',
        name: '廊坊市',
        parent_id: '130000',
        listorder: '6',
        children: [
          {
            id: '131002',
            name: '安次区',
            parent_id: '131000',
            listorder: '1',
          },
          {
            id: '131081',
            name: '霸州市',
            parent_id: '131000',
            listorder: '2',
          },
          {
            id: '131028',
            name: '大厂回族自治县',
            parent_id: '131000',
            listorder: '3',
          },
          {
            id: '131025',
            name: '大城县',
            parent_id: '131000',
            listorder: '4',
          },
          {
            id: '131003',
            name: '广阳区',
            parent_id: '131000',
            listorder: '5',
          },
          {
            id: '131022',
            name: '固安县',
            parent_id: '131000',
            listorder: '6',
          },
          {
            id: '131082',
            name: '三河市',
            parent_id: '131000',
            listorder: '7',
          },
          {
            id: '131026',
            name: '文安县',
            parent_id: '131000',
            listorder: '8',
          },
          {
            id: '131024',
            name: '香河县',
            parent_id: '131000',
            listorder: '9',
          },
          {
            id: '131023',
            name: '永清县',
            parent_id: '131000',
            listorder: '10',
          },
        ],
      },
      {
        id: '130300',
        name: '秦皇岛市',
        parent_id: '130000',
        listorder: '7',
        children: [
          {
            id: '130304',
            name: '北戴河区',
            parent_id: '130300',
            listorder: '1',
          },
          {
            id: '130322',
            name: '昌黎县',
            parent_id: '130300',
            listorder: '2',
          },
          {
            id: '130323',
            name: '抚宁县',
            parent_id: '130300',
            listorder: '3',
          },
          {
            id: '130302',
            name: '海港区',
            parent_id: '130300',
            listorder: '4',
          },
          {
            id: '130324',
            name: '卢龙县',
            parent_id: '130300',
            listorder: '5',
          },
          {
            id: '130321',
            name: '青龙满族自治县',
            parent_id: '130300',
            listorder: '6',
          },
          {
            id: '130303',
            name: '山海关区',
            parent_id: '130300',
            listorder: '7',
          },
        ],
      },
      {
        id: '130100',
        name: '石家庄市',
        parent_id: '130000',
        listorder: '8',
        children: [
          {
            id: '130102',
            name: '长安区',
            parent_id: '130100',
            listorder: '1',
          },
          {
            id: '130182',
            name: '藁城市',
            parent_id: '130100',
            listorder: '2',
          },
          {
            id: '130127',
            name: '高邑县',
            parent_id: '130100',
            listorder: '3',
          },
          {
            id: '130107',
            name: '井陉矿区',
            parent_id: '130100',
            listorder: '4',
          },
          {
            id: '130121',
            name: '井陉县',
            parent_id: '130100',
            listorder: '5',
          },
          {
            id: '130183',
            name: '晋州市',
            parent_id: '130100',
            listorder: '6',
          },
          {
            id: '130126',
            name: '灵寿县',
            parent_id: '130100',
            listorder: '7',
          },
          {
            id: '130124',
            name: '栾城县',
            parent_id: '130100',
            listorder: '8',
          },
          {
            id: '130185',
            name: '鹿泉市',
            parent_id: '130100',
            listorder: '9',
          },
          {
            id: '130131',
            name: '平山县',
            parent_id: '130100',
            listorder: '10',
          },
          {
            id: '130103',
            name: '桥东区',
            parent_id: '130100',
            listorder: '11',
          },
          {
            id: '130104',
            name: '桥西区',
            parent_id: '130100',
            listorder: '12',
          },
          {
            id: '130128',
            name: '深泽县',
            parent_id: '130100',
            listorder: '13',
          },
          {
            id: '130130',
            name: '无极县',
            parent_id: '130100',
            listorder: '14',
          },
          {
            id: '130125',
            name: '行唐县',
            parent_id: '130100',
            listorder: '15',
          },
          {
            id: '130105',
            name: '新华区',
            parent_id: '130100',
            listorder: '16',
          },
          {
            id: '130181',
            name: '辛集市',
            parent_id: '130100',
            listorder: '17',
          },
          {
            id: '130184',
            name: '新乐市',
            parent_id: '130100',
            listorder: '18',
          },
          {
            id: '130132',
            name: '元氏县',
            parent_id: '130100',
            listorder: '19',
          },
          {
            id: '130108',
            name: '裕华区',
            parent_id: '130100',
            listorder: '20',
          },
          {
            id: '130129',
            name: '赞皇县',
            parent_id: '130100',
            listorder: '21',
          },
          {
            id: '130133',
            name: '赵县',
            parent_id: '130100',
            listorder: '22',
          },
          {
            id: '130123',
            name: '正定县',
            parent_id: '130100',
            listorder: '23',
          },
        ],
      },
      {
        id: '130200',
        name: '唐山市',
        parent_id: '130000',
        listorder: '9',
        children: [
          {
            id: '130230',
            name: '曹妃甸区',
            parent_id: '130200',
            listorder: '1',
          },
          {
            id: '130207',
            name: '丰南区',
            parent_id: '130200',
            listorder: '2',
          },
          {
            id: '130208',
            name: '丰润区',
            parent_id: '130200',
            listorder: '3',
          },
          {
            id: '130204',
            name: '古冶区',
            parent_id: '130200',
            listorder: '4',
          },
          {
            id: '130205',
            name: '开平区',
            parent_id: '130200',
            listorder: '5',
          },
          {
            id: '130225',
            name: '乐亭县',
            parent_id: '130200',
            listorder: '6',
          },
          {
            id: '130224',
            name: '滦南县',
            parent_id: '130200',
            listorder: '7',
          },
          {
            id: '130223',
            name: '滦县',
            parent_id: '130200',
            listorder: '8',
          },
          {
            id: '130203',
            name: '路北区',
            parent_id: '130200',
            listorder: '9',
          },
          {
            id: '130202',
            name: '路南区',
            parent_id: '130200',
            listorder: '10',
          },
          {
            id: '130283',
            name: '迁安市',
            parent_id: '130200',
            listorder: '11',
          },
          {
            id: '130227',
            name: '迁西县',
            parent_id: '130200',
            listorder: '12',
          },
          {
            id: '130229',
            name: '玉田县',
            parent_id: '130200',
            listorder: '13',
          },
          {
            id: '130281',
            name: '遵化市',
            parent_id: '130200',
            listorder: '14',
          },
        ],
      },
      {
        id: '130500',
        name: '邢台市',
        parent_id: '130000',
        listorder: '10',
        children: [
          {
            id: '130524',
            name: '柏乡县',
            parent_id: '130500',
            listorder: '1',
          },
          {
            id: '130531',
            name: '广宗县',
            parent_id: '130500',
            listorder: '2',
          },
          {
            id: '130529',
            name: '巨鹿县',
            parent_id: '130500',
            listorder: '3',
          },
          {
            id: '130522',
            name: '临城县',
            parent_id: '130500',
            listorder: '4',
          },
          {
            id: '130535',
            name: '临西县',
            parent_id: '130500',
            listorder: '5',
          },
          {
            id: '130525',
            name: '隆尧县',
            parent_id: '130500',
            listorder: '6',
          },
          {
            id: '130581',
            name: '南宫市',
            parent_id: '130500',
            listorder: '7',
          },
          {
            id: '130527',
            name: '南和县',
            parent_id: '130500',
            listorder: '8',
          },
          {
            id: '130523',
            name: '内丘县',
            parent_id: '130500',
            listorder: '9',
          },
          {
            id: '130528',
            name: '宁晋县',
            parent_id: '130500',
            listorder: '10',
          },
          {
            id: '130532',
            name: '平乡县',
            parent_id: '130500',
            listorder: '11',
          },
          {
            id: '130502',
            name: '桥东区',
            parent_id: '130500',
            listorder: '12',
          },
          {
            id: '130503',
            name: '桥西区',
            parent_id: '130500',
            listorder: '13',
          },
          {
            id: '130534',
            name: '清河县',
            parent_id: '130500',
            listorder: '14',
          },
          {
            id: '130526',
            name: '任县',
            parent_id: '130500',
            listorder: '15',
          },
          {
            id: '130582',
            name: '沙河市',
            parent_id: '130500',
            listorder: '16',
          },
          {
            id: '130533',
            name: '威县',
            parent_id: '130500',
            listorder: '17',
          },
          {
            id: '130521',
            name: '邢台县',
            parent_id: '130500',
            listorder: '18',
          },
          {
            id: '130530',
            name: '新河县',
            parent_id: '130500',
            listorder: '19',
          },
        ],
      },
      {
        id: '130700',
        name: '张家口市',
        parent_id: '130000',
        listorder: '11',
        children: [
          {
            id: '130732',
            name: '赤城县',
            parent_id: '130700',
            listorder: '1',
          },
          {
            id: '130733',
            name: '崇礼县',
            parent_id: '130700',
            listorder: '2',
          },
        ],
      },
    ],
  },
];
